allowBuilds:
  '@datadog/native-appsec': false
  '@datadog/native-iast-taint-tracking': false
  '@datadog/native-metrics': false
  '@datadog/pprof': false
  dd-trace: false
  esbuild: true
  sharp: false
  unrs-resolver: false
